### PR TITLE
Add support for regenerating metadata

### PR DESCRIPTION
**Pull request by ndm2**
Currently metadata is only saved when a record is created, thus the data in the record becomes invalid when a file is replaced.

This problem is somewhat covert by the metadata injection that takes place after retrieving a record, however this only works when the model which has the behavior attached is queried directly, and of course the data in database should be valid anyway.

This patch adds support for regenerating metadata when a record is updated.

See also https://github.com/davidpersson/media/issues/67

### CODE REVIEW

**Comment by ReplicaObscura** [comment]
Thanks! A simple and effective fix to an issue I hadn't even noticed :)

**Comment by ReplicaObscura** [comment]
I feel bad that I haven't had time to devote to coding on this project and you have been submitting really great changes left and right. All of your PRs are incredibly appreciated, just so you know!

**Comment by ReplicaObscura** [comment]
Success! At least this PR seemed to go through CI without segfaulting.

**Comment by ndm2** [comment]
Thanks for the kind words, I'm glad that I can give something back to this project after benefiting from it for such a long time.

**Pull request merged**
