### PR TITLE
Fix filters logic

### PR DESCRIPTION
**Pull request by gBokiau**
Since as of commit d0b8f5985b8fbc587d0e57cf093bc48a0328905f the use of
different filter configurations no longer works (why not, makes it
simpler), might as well remove the corresponding functions and update
default configuration in bootstrap.

### CODE REVIEW

**Comment by ReplicaObscura** [comment]
I hadn't actually noticed that the new style of filters quit working (whoops!).

I'm not sure yet how I feel about it though--I do like the ability to use named filters specified in the model--it allows for greater flexibility and reuse.

But I also understand that the code is simpler without it. Hmm, thinking about this one.

**Comment by gBokiau** [comment]
I'm unsure myself. Any idea what was wrong with the code previous to d0b8f59 ?

**Comment by ReplicaObscura** [comment]
Good question--I neglected to do my due diligence with that pull request apparently, as I don't think I'd have let that one through if I had noticed that.

As far as I know nothing was wrong with that functionality previously, except it may not have worked as documented as I know my documentation has been seriously lacking for the things I've updated. I'd prefer to still have the option at least of using named filters rather than always doing it by type (to avoid, for instance, having to create an identical set of filters for every possible image type).

It might be more useful to have named filters assigned to fields instead of the entire model however, to allow models to support multiple media types, but I've never actually had a use case for that to be honest so I don't know for sure if it'd be worth it.

**Comment by ReplicaObscura** [comment]
This should hopefully not be needed anymore with the changes in https://github.com/bmcclure/CakePHP-Media-Plugin/issues/41 however let me know if the way it works now isn't sufficient for your needs here.

**Pull request closed without merging**
