### PR TITLE
Remove workarounds for older PHP versions

### PR DESCRIPTION
**Pull request by ndm2**
This patch removes the workarounds for PHP versions < 5.2.0 where `PATHINFO_FILENAME` support is missing. The CakePHP core already requires PHP 5.2.8 as a minimum, not to mention that this functionality is used in the `GeneratorBehaviour` class [since ages](https://github.com/davidpersson/media/commit/3dc0a99542f93e38f279f8dcd070639143cd4624#diff-c773dbc49ea9eafb6801aeea766ab820), so these workarounds should be be safe to drop.

### CODE REVIEW

**Comment by ReplicaObscura** [comment]
Good catch! Thanks for helping to clean up the code!

**Comment by ndm2** [comment]
Yet another segfault... if this keeps happening it might be something worth to investigate.

**Comment by ReplicaObscura** [comment]
Re-ran and it was successful this time. Does make me wonder why this seems to be a recurring event with this project, but there doesn't seem to be much consistency with when it fails.

**Comment by ndm2** [comment]
Yep, pretty hard to tell, though in the end it's most probably a bug (outside of this projects code) or faulty RAM. The next PR is on its way, we'll see if this keeps happening.

**Pull request merged**
