### PR TITLE
Fix issues with making versions

### PR DESCRIPTION
**Pull request by ReplicaObscura**
Looks like a good change

### CODE REVIEW

**Comment by tfiersen** [comment]
Seriously, the old behavior from the 1.x branch is extremely limiting, per model filters are way more flexible. There was no reason to remove this functionality, it was a very bad idea if you ask me.

@drewisme What was your intention? There's no description, what issues did you encounter that needed fixing? If there are any issues, then there are definitly better ways to fix them than by completely removing/disabling the functionality.

**Comment by drewisme** [comment]
@tfiersen my intention was to make it work on my fork. I never submitted a pull request so I didn't even know it was pulled. @foxxyz actually improved this: https://github.com/SideStudios/CakePHP-Media-Plugin/

**Comment by tfiersen** [comment]
@drewisme I saw it wasn't you, I was just wondering what you were trying to fix, so I could maybe fix it without removing the per-model filter functionality. So, actually there were no issues related to the original code, but only to modifications in your specific fork?

I've seen the modifications from @foxxyz, but as far as I can tell it only grabs additional filters defined in the relationship settings of a single model that has an has-many relation to the current model (in case the related models name is defined in a form field named `model`), specific filters for the current model however aren't incorporated. Overall this seems a little weird to me, it's probably ment for some very special situations.

**Comment by ReplicaObscura** [comment]
I must have gotten a bit overzealous and pulled it in without paying enough attention to the functionality it removed. Should this simply be reverted to how it was, or is there a better way to approach whatever issue this was solving?

**Pull request merged**
