### PR TITLE
Add composer support

### PR DESCRIPTION
**Pull request by ndm2**
This patch adds initial support for composer. Hopefully I got this right.

In order for package consumers to have this work out of the box, ie without additionally [adding the repository URL to the local composer configuration](https://getcomposer.org/doc/05-repositories.md#vcs), the repository still needs to be registered with https://packagist.org. I guess anyone can do that, not sure, I never did it before.

Once merged and registered it should be possible to include the plugin using for example

``` json
{
    "require": {
        "bmcclure/cakephp-media-plugin": "2.*@dev"
    }
}
```

### CODE REVIEW

**Comment by ReplicaObscura** [comment]
Thanks, sorry it took a while to merge this!

**Comment by ndm2** [comment]
For easier integration this still needs to be registered with packagist, however it seems to be not recommended to submit repositories that you don't own, also this needs a GitHub Service Hook setup for the repository in order to ensure that the packages are being updated in time, so this would need to be done by you.

See also https://packagist.org/about

**Comment by ReplicaObscura** [comment]
Thanks! I will get this set up.

**Comment by ReplicaObscura** [comment]
Should be all set at Packagist now: https://packagist.org/packages/bmcclure/cakephp-media-plugin

I set up the service hook, though it still says it's not set up when I log into Packagist. I'm assuming after the next commit maybe that message will go away.

**Comment by ndm2** [comment]
Works fine :thumbsup:

**Comment by Oxicode** [comment]
:+1:

**Pull request merged**
